# Generated by Django 5.2.3 on 2025-06-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_billinginfo_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='cleint_name',
            field=models.CharField(default='cleint', max_length=50),
        ),
    ]
