# Generated by Django 4.2.7 on 2025-06-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('duration', 'Case Duration'), ('revenue', 'Revenue Generated'), ('client_satisfaction', 'Client Satisfaction'), ('complexity_score', 'Complexity Score'), ('success_rate', 'Success Rate'), ('time_spent', 'Time Spent'), ('document_count', 'Document Count'), ('audience_count', 'Audience Count')], max_length=30)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('metric_text', models.CharField(blank=True, max_length=200)),
                ('metric_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Analytic',
                'verbose_name_plural': 'Case Analytics',
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cases_opened', models.PositiveIntegerField(default=0)),
                ('cases_closed', models.PositiveIntegerField(default=0)),
                ('active_cases', models.PositiveIntegerField(default=0)),
                ('average_case_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_case_duration', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_billable_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Analytic',
                'verbose_name_plural': 'Revenue Analytics',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
