# Generated by Django 5.2.3 on 2025-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_code',
            field=models.CharField(blank=True, help_text="Code d'Activité", max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nif',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nis',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Statistique", max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rc',
            field=models.CharField(blank=True, help_text='Registre de Commerce', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tva',
            field=models.CharField(blank=True, help_text='Numéro TVA', max_length=50),
        ),
    ]
