# Generated by Django 4.2.7 on 2025-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgerianCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name_fr', models.CharField(max_length=200)),
                ('court_name_ar', models.CharField(max_length=200)),
                ('court_level', models.CharField(choices=[('premiere', 'Première Instance'), ('appel', 'Appel'), ('cassation', 'Cassation')], max_length=20)),
                ('jurisdiction_type', models.CharField(choices=[('civil', 'Civil'), ('penal', 'Pénal'), ('administratif', 'Administratif'), ('commercial', 'Commercial'), ('famille', 'Famille'), ('social', 'Social'), ('maritime', 'Maritime'), ('militaire', 'Militaire')], max_length=30)),
                ('wilaya', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('president', models.CharField(blank=True, max_length=200)),
                ('vice_president', models.CharField(blank=True, max_length=200)),
                ('procureur', models.CharField(blank=True, max_length=200)),
                ('secretary_general', models.CharField(blank=True, max_length=200)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Algerian Court',
                'verbose_name_plural': 'Algerian Courts',
                'ordering': ['wilaya', 'court_name_fr'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('tva', 'TVA - Taxe sur la Valeur Ajoutée'), ('irg', 'IRG - Impôt sur le Revenu Global'), ('ibs', 'IBS - Impôt sur les Bénéfices des Sociétés'), ('tap', "TAP - Taxe sur l'Activité Professionnelle"), ('versement_forfaitaire', 'Versement Forfaitaire'), ('timbre', 'Droit de Timbre'), ('enregistrement', "Droit d'Enregistrement")], max_length=30)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description_fr', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
                'ordering': ['tax_type', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='LegalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name_fr', models.CharField(max_length=300)),
                ('procedure_name_ar', models.CharField(max_length=300)),
                ('procedure_type', models.CharField(choices=[('civil', 'Procédure Civile'), ('penal', 'Procédure Pénale'), ('administrative', 'Procédure Administrative'), ('commercial', 'Procédure Commerciale'), ('famille', 'Procédure de Famille'), ('execution', "Procédure d'Exécution"), ('arbitrage', 'Arbitrage'), ('mediation', 'Médiation')], max_length=30)),
                ('court_level', models.CharField(choices=[('premiere', 'Première Instance'), ('appel', 'Appel'), ('cassation', 'Cassation')], max_length=20)),
                ('description_fr', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('template_content_fr', models.TextField(blank=True)),
                ('template_content_ar', models.TextField(blank=True)),
                ('required_documents', models.JSONField(default=list)),
                ('timeline_days', models.PositiveIntegerField(blank=True, null=True)),
                ('fees_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fees_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('legal_references', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_procedures', models.ManyToManyField(blank=True, to='legal_framework.legalprocedure')),
            ],
        ),
        migrations.CreateModel(
            name='AlgerianLegalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name_fr', models.CharField(max_length=200)),
                ('code_name_ar', models.CharField(max_length=200)),
                ('code_type', models.CharField(choices=[('civil', 'Code Civil'), ('penal', 'Code Pénal'), ('procedure_civile', 'Code de Procédure Civile'), ('procedure_penale', 'Code de Procédure Pénale'), ('commerce', 'Code de Commerce'), ('travail', 'Code du Travail'), ('famille', 'Code de la Famille'), ('maritime', 'Code Maritime'), ('aerien', 'Code Aérien'), ('douanes', 'Code des Douanes'), ('impots', 'Code des Impôts'), ('investissement', 'Code des Investissements'), ('environnement', "Code de l'Environnement"), ('urbanisme', "Code de l'Urbanisme")], max_length=50)),
                ('article_number', models.CharField(blank=True, max_length=20)),
                ('article_title_fr', models.CharField(blank=True, max_length=500)),
                ('article_title_ar', models.CharField(blank=True, max_length=500)),
                ('article_content_fr', models.TextField(blank=True)),
                ('article_content_ar', models.TextField(blank=True)),
                ('related_articles', models.JSONField(blank=True, default=list)),
                ('jurisprudence_references', models.JSONField(blank=True, default=list)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Algerian Legal Code',
                'verbose_name_plural': 'Algerian Legal Codes',
                'ordering': ['code_type', 'article_number'],
                'unique_together': {('code_type', 'article_number')},
            },
        ),
    ]
