# Generated by Django 4.2.7 on 2025-06-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_task_reminders', models.BooleanField(default=True)),
                ('email_audience_reminders', models.BooleanField(default=True)),
                ('email_case_updates', models.BooleanField(default=True)),
                ('email_payment_updates', models.BooleanField(default=True)),
                ('email_document_shares', models.BooleanField(default=True)),
                ('app_task_reminders', models.BooleanField(default=True)),
                ('app_audience_reminders', models.BooleanField(default=True)),
                ('app_case_updates', models.BooleanField(default=True)),
                ('app_payment_updates', models.BooleanField(default=True)),
                ('app_document_shares', models.BooleanField(default=True)),
                ('sms_urgent_only', models.BooleanField(default=False)),
                ('daily_digest', models.BooleanField(default=True)),
                ('daily_digest_time', models.TimeField(default='09:00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('task_due', 'Task Due'), ('task_overdue', 'Task Overdue'), ('audience_reminder', 'Audience Reminder'), ('case_update', 'Case Update'), ('document_shared', 'Document Shared'), ('payment_received', 'Payment Received'), ('invoice_overdue', 'Invoice Overdue'), ('new_message', 'New Message'), ('system', 'System Notification')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
