# Generated by Django 5.2.3 on 2025-07-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdiction',
            name='level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='type_fr',
            field=models.CharField(default='', max_length=50),
        ),
    ]
