# Generated by Django 5.2.3 on 2025-06-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='case',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
    ]
